# Generated by Django 3.2.3 on 2023-07-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={},
        ),
        migrations.RemoveField(
            model_name='ingredientrecipe',
            name='amount',
        ),
    ]
