# Generated by Django 3.2.3 on 2023-08-05 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230805_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Выберете хотя бы 1 ингредиент.'), django.core.validators.MaxValueValidator(3000, message='Максимальное количество ингредиента - 3000 г.')], verbose_name='Количество'),
        ),
    ]
