# Generated by Django 3.2.3 on 2023-07-31 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230731_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Выберете хотя бы 1 ингредиент.'), django.core.validators.MaxValueValidator(100, message='Максимальное количество ингредиента - 100.')], verbose_name='Количество'),
        ),
    ]
