# Generated by Django 3.2.3 on 2023-07-29 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Выберете хотя бы 1 ингредиент.'), django.core.validators.MaxValueValidator(100, message='Максимальное количество ингредиента - 100.')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное время приготовления 1 минута.'), django.core.validators.MaxValueValidator(1440, message='Максимальное время приготовления 1440 минут (1 день).')], verbose_name='Время приготовления'),
        ),
    ]
