# Generated by Django 3.2.3 on 2023-08-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230803_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
